### ISSUE TITLE
Dell XPS13 Ubuntu 18.04 tries (incorrectly) to load BCM20702A1-0a5c-216f.hcd

### ISSUE THREAD

**Issue by tagru** [winterheart/broadcom-bt-firmware#10]
I tried to retrieve the correct firmware from this repo, due to this message in dmesg

````
[  197.522851] Bluetooth: hci0: BCM: chip id 63
[  197.523860] Bluetooth: hci0: BCM: features 0x07
[  197.539929] Bluetooth: hci0: BCM20702A
[  197.540910] Bluetooth: hci0: BCM20702A1 (001.002.014) build 0000
[  197.588446] bluetooth hci0: Direct firmware load for brcm/BCM20702A1-0a5c-216f.hcd failed with error -2
````

After copying frimware BCM20702A1-0a5c-216f.hcd  to /lib/firmware/brcm and loading it with

`sudo modprobe -v btusb`

switching bluetooth on did not work anymore.

After some digging, I found another firmware called BCM20702A0-0a5c-216f.hcd here:

[https://github.com/hg8/bluetooth-firmware-XPS13-9343](https://github.com/hg8/bluetooth-firmware-XPS13-9343)

Since it still tried to load the BCM20702A1 version, I simply renamed the A0 version to A1 and now everything works as expected.

Is this a known issue and should the A0 version be added to this repo with a notice that renaming is needed? Or is this the completely wrong place for this issue?

**Comment by winterheart** [comment]
Both binaries are same:
```
md5sum BCM20702A0-0a5c-216f.hcd BCM20702A1-0a5c-216f.hcd
356ecc4d52b344109b55b3c96d6ec4d0  BCM20702A0-0a5c-216f.hcd
356ecc4d52b344109b55b3c96d6ec4d0  BCM20702A1-0a5c-216f.hcd
```
You did something wrong. Try to reboot system after copying firmware.
