### ISSUE TITLE
BCM2046

### ISSUE THREAD

**Issue by SuNNjek** [winterheart/broadcom-bt-firmware#12]
Hi,

is there any way to get support for the BCM2046? I have an old laptop with this card but it's not working with Linux.

**Comment by winterheart** [comment]
Hello.
BCM2046 not related with broadcom-bt-firmware files. Try to use this: https://ubuntuforums.org/showthread.php?t=2410564, https://www.dell.com/community/Networking-Internet-Bluetooth/Dell-XPS-M1530-Bluetooth-355-and-Windows-7/td-p/3217683
