### ISSUE TITLE
Unable to works with Asus BT400 bluetooth dongle on Proxmox

### ISSUE THREAD

**Issue by vpomax** [winterheart/broadcom-bt-firmware#14]
I’ve been trying for days to install an Asus BT400 USB dongle on a NUC on which I have Proxmox with a VM with Hassio directly installed.
After several attempts I was able to install the specific drivers in the /lib/firmware/brcm folder … but Hassio doesn’t see the bluetooth key.

If I use…

Copy to clipboard
root@proxmox:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04cf:0022 Myson Century, Inc. OCZ Alchemy Series Elixir II Keyboard
Bus 001 Device 003: ID 046d:c52f Logitech, Inc. Unifying Receiver
Bus 001 Device 002: ID 0b05:17cb ASUSTek Computer, Inc. Broadcom BCM20702A0 Bluetooth
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
If I use…

Copy to clipboard
root@proxmox:~# service bluetooth status
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-11-02 09:15:30 CET; 5min ago
     Docs: man:bluetoothd(8)
 Main PID: 693 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   Memory: 3.2M
   CGroup: /system.slice/bluetooth.service
           └─693 /usr/lib/bluetooth/bluetoothd --noplugin=sap

Nov 02 09:15:30 proxmox systemd[1]: Starting Bluetooth service...
Nov 02 09:15:30 proxmox bluetoothd[693]: Bluetooth daemon 5.50
Nov 02 09:15:30 proxmox systemd[1]: Started Bluetooth service.
Nov 02 09:15:30 proxmox bluetoothd[693]: Starting SDP server
Nov 02 09:15:30 proxmox bluetoothd[693]: Excluding (cli) sap
Nov 02 09:15:30 proxmox bluetoothd[693]: Bluetooth management interface 1.14 initialized
If I use…

Copy to clipboard
root@proxmox:~# dmesg | grep -i bluetooth
[    2.218574] usb 1-2: Product: BCM920702 Bluetooth 4.0
[    4.983349] Bluetooth: Core ver 2.22
[    4.983362] Bluetooth: HCI device and connection manager initialized
[    4.983365] Bluetooth: HCI socket layer initialized
[    4.983367] Bluetooth: L2CAP socket layer initialized
[    4.983369] Bluetooth: SCO socket layer initialized
[    5.101433] Bluetooth: hci0: BCM: chip id 63
[    5.102431] Bluetooth: hci0: BCM: features 0x07
[    5.118451] Bluetooth: hci0: proxmox
[    5.119434] Bluetooth: hci0: BCM20702A1 (001.002.014) build 1467
[    5.885444] Bluetooth: hci0: BCM20702A1 (001.002.014) build 1467
[    5.901432] Bluetooth: hci0: Broadcom Bluetooth Device
[    5.990679] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    5.990680] Bluetooth: BNEP filters: protocol multicast
[    5.990683] Bluetooth: BNEP socket layer initialized
[   10.653095] Bluetooth: hci0: urb 000000002d8229a6 failed to resubmit (2)
but if I use

Copy to clipboard
root@proxmox:~# hcitool scan
Device is not available: No such device
if I use

Copy to clipboard
root@proxmox:~# hcitool dev
Devices:
If I use…

Copy to clipboard
root@proxmox:~# systemctl status hciuart.service
Unit hciuart.service could not be found.
If I try to install it

Copy to clipboard
root@proxmox:~# sudo apt-get install hciuart.service
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hciuart.service
E: Couldn't find any package by glob 'hciuart.service'
E: Couldn't find any package by regex 'hciuart.service'
Can someone help me?

**Comment by winterheart** [comment]
I don't see any problems with BT firmware since I have same Asus dongle. Seems you have problems with bluetooth software. You need to read documentation about Bluetooth configuration on Proxmox (or Debian/Ubuntu). I doubt that VM can handle any non-standard periferal though.
