### ISSUE TITLE
"Failed to Send Firmware Data -110"

### ISSUE THREAD

**Issue by FaizShah** [winterheart/broadcom-bt-firmware#20]
Hi,

I'm on ubuntu 19.10 on a thinkpad t480. My ubuntu won't start and it shows an error on startup that says "Bluetooth: hci0: Failed to send firmware data (-110)"

I tried trying to figure out my bluetooth type from the dmesg as recommended but it doesn't show the type of bluetooth device it only shows it loading the firmware "Found device firmware: intel/ibt-12-16.sfi" 

Any idea how I can fix this?

**Comment by winterheart** [comment]
Hello.
As I can see, T480 uses Intel Wireless Bluetooth, not related to Broadcom Bluetooth firmware. Can't help here.

**Comment by cheako** [comment]
I'm on intel as well, Wi-Fi 6 AX200 160MHz.  Can you add a link to where google should send ppl?
