### ISSUE TITLE
Acer Aspire bluetooth firmware BCM20702A1-0489-e033.hcd

### ISSUE THREAD

**Issue by blue-assassin** [winterheart/broadcom-bt-firmware#25]
I need a download link to a BCM20702A1-0489-e033.hcd firmware i have searched everywhere for this and it seems that only this version is mising i've tried BCM20702A1-0489-e032.hcd but that also didn't work

**Comment by winterheart** [comment]
Hello.

According to Windows INF file, your device don't need firmware:
```
%BtUSB.DeviceDesc%=BCBTUsbDriverInstall,    USB\VID_0489&Pid_E033       ; Acer 20702 Serial FLASH
```
`BCBTUsbDriverInstall` entry don't have any firmware entries.
