### ISSUE TITLE
BEGIN failed--compilation aborted at tools/bt-fw-converter.pl line 33.

### ISSUE THREAD

**Issue by noida77** [winterheart/broadcom-bt-firmware#38]
not configuring well there might be some issu with thier addational files

help me to solve this issue

**Comment by noida77** [comment]
BEGIN failed--compilation aborted at tools/bt-fw-converter.pl line 33.

**Comment by winterheart** [comment]
Hello.
What do you try exactly? `tools/bt-fw-converter.pl` not intended to use for users. If you have Broadcom BT device, please, just follow instruction about installation: 

* [Installation with package manager](https://github.com/winterheart/broadcom-bt-firmware#installation)
* [Manual installation](https://github.com/winterheart/broadcom-bt-firmware#detection-and-manual-installation)
