### ISSUE TITLE
BCM43430A1 aka BT firmware for Pi3 missing

### ISSUE THREAD

**Issue by samip5** [winterheart/broadcom-bt-firmware#43]
**Describe the bug**
Missing firmware for the Pi3, aka BCM43430A1

**Comment by winterheart** [comment]
Hello. This is post-Broadcom chipsets created by Cypress after Broadcom sold Bluetooth-related business. Firmwares for this generation of chipsets distributes separately.
Try to use https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi or check your distribution documentation regarding fetching firmware files for Raspberry Pi. See also https://forums.raspberrypi.com/viewtopic.php?t=244207
