### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pjvalla** [winterheart/broadcom-bt-firmware#5]
Getting this error message when running the generate_files.sh script

```
phil:broadcom-bt-firmware$ . ./generate_files.sh 
Make sure that you downloaded and unpacked into source directory latest drivers from Broadcom site.
In source directory should be bcbtums.inf and *.hex files.
Other stuff is not required.

Removing old hcd-files...

Generating new hcd-files...
No such file or directory on source/bcbtums.inf at tools/bt-fw-converter.pl line 80.

Done!
```

`bcbtums.inf` is not in the `source directory`.  I am  pulling from `master`

**Comment by winterheart** [comment]
You don't need to run generate_files.sh get hcd files. Just download needed one from brcm directory. generate_files.sh required for packagers, not for end-users.
